package com.lxt.model;

import java.util.Date;

public class ChatFriend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_chat_friend.ID
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_chat_friend.USER_ID
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_chat_friend.FRIEND_ID
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    private String friendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_chat_friend.FRIEND_CATEGORY_ID
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    private String friendCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_chat_friend.MEMO
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_chat_friend.INSERT_TIME
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_chat_friend.UPDATE_TIME
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_chat_friend.SORT_SEQ
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    private Integer sortSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_chat_friend.ID
     *
     * @return the value of lxt_chat_friend.ID
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_chat_friend.ID
     *
     * @param id the value for lxt_chat_friend.ID
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_chat_friend.USER_ID
     *
     * @return the value of lxt_chat_friend.USER_ID
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_chat_friend.USER_ID
     *
     * @param userId the value for lxt_chat_friend.USER_ID
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_chat_friend.FRIEND_ID
     *
     * @return the value of lxt_chat_friend.FRIEND_ID
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public String getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_chat_friend.FRIEND_ID
     *
     * @param friendId the value for lxt_chat_friend.FRIEND_ID
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public void setFriendId(String friendId) {
        this.friendId = friendId == null ? null : friendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_chat_friend.FRIEND_CATEGORY_ID
     *
     * @return the value of lxt_chat_friend.FRIEND_CATEGORY_ID
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public String getFriendCategoryId() {
        return friendCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_chat_friend.FRIEND_CATEGORY_ID
     *
     * @param friendCategoryId the value for lxt_chat_friend.FRIEND_CATEGORY_ID
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public void setFriendCategoryId(String friendCategoryId) {
        this.friendCategoryId = friendCategoryId == null ? null : friendCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_chat_friend.MEMO
     *
     * @return the value of lxt_chat_friend.MEMO
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_chat_friend.MEMO
     *
     * @param memo the value for lxt_chat_friend.MEMO
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_chat_friend.INSERT_TIME
     *
     * @return the value of lxt_chat_friend.INSERT_TIME
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_chat_friend.INSERT_TIME
     *
     * @param insertTime the value for lxt_chat_friend.INSERT_TIME
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_chat_friend.UPDATE_TIME
     *
     * @return the value of lxt_chat_friend.UPDATE_TIME
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_chat_friend.UPDATE_TIME
     *
     * @param updateTime the value for lxt_chat_friend.UPDATE_TIME
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_chat_friend.SORT_SEQ
     *
     * @return the value of lxt_chat_friend.SORT_SEQ
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public Integer getSortSeq() {
        return sortSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_chat_friend.SORT_SEQ
     *
     * @param sortSeq the value for lxt_chat_friend.SORT_SEQ
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    public void setSortSeq(Integer sortSeq) {
        this.sortSeq = sortSeq;
    }
}