package com.lxt.model;

public class LxtChatGroupUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_chat_group_user.GROUP_ID
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_chat_group_user.USER_ID
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_chat_group_user.GROUP_ID
     *
     * @return the value of lxt_chat_group_user.GROUP_ID
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_chat_group_user.GROUP_ID
     *
     * @param groupId the value for lxt_chat_group_user.GROUP_ID
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_chat_group_user.USER_ID
     *
     * @return the value of lxt_chat_group_user.USER_ID
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_chat_group_user.USER_ID
     *
     * @param userId the value for lxt_chat_group_user.USER_ID
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}