package com.lxt.dao.mapper;

import com.lxt.model.ChatRecord;
import com.lxt.model.ChatRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    long countByExample(ChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int deleteByExample(ChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int insert(ChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int insertSelective(ChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    List<ChatRecord> selectByExample(ChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    ChatRecord selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") ChatRecord record, @Param("example") ChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int updateByExample(@Param("record") ChatRecord record, @Param("example") ChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int updateByPrimaryKeySelective(ChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int updateByPrimaryKey(ChatRecord record);
}