package com.lxt.dao.mapper;

import com.lxt.model.ChatGroupUserExample;
import com.lxt.model.ChatGroupUserKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatGroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    long countByExample(ChatGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int deleteByExample(ChatGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int deleteByPrimaryKey(ChatGroupUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int insert(ChatGroupUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int insertSelective(ChatGroupUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    List<ChatGroupUserKey> selectByExample(ChatGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") ChatGroupUserKey record, @Param("example") ChatGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int updateByExample(@Param("record") ChatGroupUserKey record, @Param("example") ChatGroupUserExample example);
}