package com.lxt.dao.mapper;

import com.lxt.model.LxtChatGroupUserExample;
import com.lxt.model.LxtChatGroupUserKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LxtChatGroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    long countByExample(LxtChatGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByExample(LxtChatGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByPrimaryKey(LxtChatGroupUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insert(LxtChatGroupUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insertSelective(LxtChatGroupUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    List<LxtChatGroupUserKey> selectByExample(LxtChatGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") LxtChatGroupUserKey record, @Param("example") LxtChatGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_group_user
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExample(@Param("record") LxtChatGroupUserKey record, @Param("example") LxtChatGroupUserExample example);
}