package com.lxt.dao.mapper;

import com.lxt.model.LxtChatRecord;
import com.lxt.model.LxtChatRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LxtChatRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    long countByExample(LxtChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByExample(LxtChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insert(LxtChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insertSelective(LxtChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    List<LxtChatRecord> selectByExample(LxtChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    LxtChatRecord selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") LxtChatRecord record, @Param("example") LxtChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExample(@Param("record") LxtChatRecord record, @Param("example") LxtChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKeySelective(LxtChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKey(LxtChatRecord record);
}