package com.lxt.dao.mapper;

import com.lxt.model.LxtDictionaryType;
import com.lxt.model.LxtDictionaryTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LxtDictionaryTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary_type
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    long countByExample(LxtDictionaryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary_type
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByExample(LxtDictionaryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary_type
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByPrimaryKey(Integer type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary_type
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insert(LxtDictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary_type
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insertSelective(LxtDictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary_type
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    List<LxtDictionaryType> selectByExample(LxtDictionaryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary_type
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    LxtDictionaryType selectByPrimaryKey(Integer type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary_type
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") LxtDictionaryType record, @Param("example") LxtDictionaryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary_type
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExample(@Param("record") LxtDictionaryType record, @Param("example") LxtDictionaryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary_type
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKeySelective(LxtDictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary_type
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKey(LxtDictionaryType record);
}