package com.lxt.dao.mapper;

import com.lxt.model.LxtNode;
import com.lxt.model.LxtNodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LxtNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_node
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    long countByExample(LxtNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_node
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByExample(LxtNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_node
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByPrimaryKey(String nodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_node
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insert(LxtNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_node
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insertSelective(LxtNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_node
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    List<LxtNode> selectByExampleWithBLOBs(LxtNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_node
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    List<LxtNode> selectByExample(LxtNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_node
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    LxtNode selectByPrimaryKey(String nodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_node
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") LxtNode record, @Param("example") LxtNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_node
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") LxtNode record, @Param("example") LxtNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_node
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExample(@Param("record") LxtNode record, @Param("example") LxtNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_node
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKeySelective(LxtNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_node
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(LxtNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_node
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKey(LxtNode record);
}