package com.lxt.dao.mapper;

import com.lxt.model.LxtOrganization;
import com.lxt.model.LxtOrganizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LxtOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_organization
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    long countByExample(LxtOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_organization
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByExample(LxtOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_organization
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByPrimaryKey(String orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_organization
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insert(LxtOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_organization
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insertSelective(LxtOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_organization
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    List<LxtOrganization> selectByExample(LxtOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_organization
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    LxtOrganization selectByPrimaryKey(String orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_organization
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") LxtOrganization record, @Param("example") LxtOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_organization
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExample(@Param("record") LxtOrganization record, @Param("example") LxtOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_organization
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKeySelective(LxtOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_organization
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKey(LxtOrganization record);
}