package com.lxt.dao.mapper;

import com.lxt.model.LxtProcess;
import com.lxt.model.LxtProcessExample;
import com.lxt.model.LxtProcessWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LxtProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    long countByExample(LxtProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByExample(LxtProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByPrimaryKey(String processId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insert(LxtProcessWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insertSelective(LxtProcessWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    List<LxtProcessWithBLOBs> selectByExampleWithBLOBs(LxtProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    List<LxtProcess> selectByExample(LxtProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    LxtProcessWithBLOBs selectByPrimaryKey(String processId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") LxtProcessWithBLOBs record, @Param("example") LxtProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") LxtProcessWithBLOBs record, @Param("example") LxtProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExample(@Param("record") LxtProcess record, @Param("example") LxtProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKeySelective(LxtProcessWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(LxtProcessWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKey(LxtProcess record);
}