package com.lxt.dao.mapper;

import com.lxt.model.LxtProcessCategory;
import com.lxt.model.LxtProcessCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LxtProcessCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    long countByExample(LxtProcessCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByExample(LxtProcessCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insert(LxtProcessCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insertSelective(LxtProcessCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    List<LxtProcessCategory> selectByExample(LxtProcessCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    LxtProcessCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") LxtProcessCategory record, @Param("example") LxtProcessCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExample(@Param("record") LxtProcessCategory record, @Param("example") LxtProcessCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKeySelective(LxtProcessCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKey(LxtProcessCategory record);
}