package com.lxt.dao.mapper;

import com.lxt.model.LxtUserSetting;
import com.lxt.model.LxtUserSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LxtUserSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    long countByExample(LxtUserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByExample(LxtUserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insert(LxtUserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int insertSelective(LxtUserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    List<LxtUserSetting> selectByExample(LxtUserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    LxtUserSetting selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") LxtUserSetting record, @Param("example") LxtUserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByExample(@Param("record") LxtUserSetting record, @Param("example") LxtUserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKeySelective(LxtUserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 11:50:24 CST 2017
     */
    int updateByPrimaryKey(LxtUserSetting record);
}