package com.lxt.dao.mapper;

import com.lxt.model.ProcessCategory;
import com.lxt.model.ProcessCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcessCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    long countByExample(ProcessCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int deleteByExample(ProcessCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int insert(ProcessCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int insertSelective(ProcessCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    List<ProcessCategory> selectByExample(ProcessCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    ProcessCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") ProcessCategory record, @Param("example") ProcessCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int updateByExample(@Param("record") ProcessCategory record, @Param("example") ProcessCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int updateByPrimaryKeySelective(ProcessCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_process_category
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int updateByPrimaryKey(ProcessCategory record);
}