package com.lxt.dao.mapper;

import com.lxt.model.UserSetting;
import com.lxt.model.UserSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    long countByExample(UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int deleteByExample(UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int insert(UserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int insertSelective(UserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    List<UserSetting> selectByExample(UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    UserSetting selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserSetting record, @Param("example") UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int updateByExample(@Param("record") UserSetting record, @Param("example") UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int updateByPrimaryKeySelective(UserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbg.generated Thu Jul 13 14:57:12 CST 2017
     */
    int updateByPrimaryKey(UserSetting record);
}